package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"

	"github.com/monkeydioude/donut/config"
)

func generate(outputFile string, pkgName string, loop func(*bytes.Buffer)) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)
	buf.WriteString("const (\n")
	loop(&buf)
	buf.WriteString(")\n")
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	dir, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}
	outPath := filepath.Join(dir, outputFile)
	if err := os.WriteFile(outPath, formatted, 0644); err != nil {
		log.Fatal(err)
	}
}

func main() {
	generate(
		"../internal/consts/controls/controls_mapping.go",
		"controls",
		func(buf *bytes.Buffer) {
			for k := range config.Controls.KeyMapping {
				fmt.Fprintf(buf, "\t%s = \"%s\"\n", k, k)
			}
		},
	)
	generate(
		"../internal/consts/tiles/tiles_mapping.go",
		"tiles",
		func(buf *bytes.Buffer) {
			for k, v := range config.Tiles.Mapping {
				fmt.Fprintf(buf, "\t%s = %d\n", v.Name, k)
			}
		},
	)
}
