package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"

	"github.com/monkeydioude/donut/config"
)

const outputFileName = "../internal/consts/tiles/tiles_mapping.go"

func main() {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	buf.WriteString("package tiles\n\n")
	buf.WriteString("const (\n")
	for k, v := range config.Tiles.Mapping {
		buf.WriteString(fmt.Sprintf("\t%s int = %d\n", k, v.ID))
	}
	buf.WriteString(")\n")
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	dir, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}
	outPath := filepath.Join(dir, outputFileName)
	if err := os.WriteFile(outPath, formatted, 0644); err != nil {
		log.Fatal(err)
	}
}
