package controls

import "github.com/hajimehoshi/ebiten/v2"

var KeyNameToEbitenKey = map[string]ebiten.Key{
	"A": ebiten.KeyA,
	"B": ebiten.KeyB,
	"C": ebiten.KeyC,
	"D": ebiten.KeyD,
	"E": ebiten.KeyE,
	"F": ebiten.KeyF,
	"G": ebiten.KeyG,
	"H": ebiten.KeyH,
	"I": ebiten.KeyI,
	"J": ebiten.KeyJ,
	"K": ebiten.KeyK,
	"L": ebiten.KeyL,
	"M": ebiten.KeyM,
	"N": ebiten.KeyN,
	"O": ebiten.KeyO,
	"P": ebiten.KeyP,
	"Q": ebiten.KeyQ,
	"R": ebiten.KeyR,
	"S": ebiten.KeyS,
	"T": ebiten.KeyT,
	"U": ebiten.KeyU,
	"V": ebiten.KeyV,
	"W": ebiten.KeyW,
	"X": ebiten.KeyX,
	"Y": ebiten.KeyY,
	"Z": ebiten.KeyZ,

	"0": ebiten.Key0,
	"1": ebiten.Key1,
	"2": ebiten.Key2,
	"3": ebiten.Key3,
	"4": ebiten.Key4,
	"5": ebiten.Key5,
	"6": ebiten.Key6,
	"7": ebiten.Key7,
	"8": ebiten.Key8,
	"9": ebiten.Key9,

	"Space":     ebiten.KeySpace,
	"Enter":     ebiten.KeyEnter,
	"Escape":    ebiten.KeyEscape,
	"Tab":       ebiten.KeyTab,
	"Backspace": ebiten.KeyBackspace,
	"Insert":    ebiten.KeyInsert,
	"Delete":    ebiten.KeyDelete,
	"Right":     ebiten.KeyRight,
	"Left":      ebiten.KeyLeft,
	"Down":      ebiten.KeyDown,
	"Up":        ebiten.KeyUp,
	"PageUp":    ebiten.KeyPageUp,
	"PageDown":  ebiten.KeyPageDown,
	"Home":      ebiten.KeyHome,
	"End":       ebiten.KeyEnd,

	"CapsLock":    ebiten.KeyCapsLock,
	"ScrollLock":  ebiten.KeyScrollLock,
	"NumLock":     ebiten.KeyNumLock,
	"PrintScreen": ebiten.KeyPrintScreen,
	"Pause":       ebiten.KeyPause,

	"F1":  ebiten.KeyF1,
	"F2":  ebiten.KeyF2,
	"F3":  ebiten.KeyF3,
	"F4":  ebiten.KeyF4,
	"F5":  ebiten.KeyF5,
	"F6":  ebiten.KeyF6,
	"F7":  ebiten.KeyF7,
	"F8":  ebiten.KeyF8,
	"F9":  ebiten.KeyF9,
	"F10": ebiten.KeyF10,
	"F11": ebiten.KeyF11,
	"F12": ebiten.KeyF12,

	"Shift":        ebiten.KeyShift,
	"Control":      ebiten.KeyControl,
	"Alt":          ebiten.KeyAlt,
	"Semicolon":    ebiten.KeySemicolon,
	"Apostrophe":   ebiten.KeyApostrophe,
	"GraveAccent":  ebiten.KeyGraveAccent,
	"Comma":        ebiten.KeyComma,
	"Period":       ebiten.KeyPeriod,
	"Slash":        ebiten.KeySlash,
	"Backslash":    ebiten.KeyBackslash,
	"LeftBracket":  ebiten.KeyLeftBracket,
	"RightBracket": ebiten.KeyRightBracket,
	"Minus":        ebiten.KeyMinus,
	"Equal":        ebiten.KeyEqual,

	// Keypad keys
	"KP0": ebiten.KeyKP0,
	"KP1": ebiten.KeyKP1,
	"KP2": ebiten.KeyKP2,
	"KP3": ebiten.KeyKP3,
	"KP4": ebiten.KeyKP4,
	"KP5": ebiten.KeyKP5,
	"KP6": ebiten.KeyKP6,
	"KP7": ebiten.KeyKP7,
	"KP8": ebiten.KeyKP8,
	"KP9": ebiten.KeyKP9,

	"KPDecimal":  ebiten.KeyKPDecimal,
	"KPEnter":    ebiten.KeyKPEnter,
	"KPEqual":    ebiten.KeyKPEqual,
	"KPMultiply": ebiten.KeyKPMultiply,
	"KPAdd":      ebiten.KeyKPAdd,
	"KPSubtract": ebiten.KeyKPSubtract,
	"KPDivide":   ebiten.KeyKPDivide,

	// Extra keys for completeness:
	"Menu":         ebiten.KeyMenu,
	"LeftControl":  ebiten.KeyControlLeft,
	"RightControl": ebiten.KeyControlRight,
	"LeftShift":    ebiten.KeyShiftLeft,
	"RightShift":   ebiten.KeyShiftRight,
	"LeftAlt":      ebiten.KeyAltLeft,
	"RightAlt":     ebiten.KeyAltRight,
}
