// Code generated by go generate; DO NOT EDIT.
package tiles

const (
	Empty            = 0
	Dirt             = 1
	Grass            = 2
	Water            = 3
	Stone            = 4
	GrassWithFlowers = 5
)
