// Code generated by go generate; DO NOT EDIT.
package tiles

const (
	Water            int = 3
	Stone            int = 4
	GrassWithFlowers int = 5
	Empty            int = 0
	Dirt             int = 1
	Grass            int = 2
)
