// Code generated by go generate; DO NOT EDIT.
package controls

const (
	ZoomReset = "ZoomReset"
	Up        = "Up"
	Down      = "Down"
	Left      = "Left"
	Right     = "Right"
	ZoomIn    = "ZoomIn"
	ZoomOut   = "ZoomOut"
)
